import type { TaskAnalysis, Tier } from "../types"

/**
 * 60 golden test cases across 7 categories:
 *   A. Obvious tier (base calibration) — 10
 *   B. Deceptively simple (look easy, risky) — 10
 *   C. Deceptively complex (look hard, mechanical) — 8
 *   D. Linguistic ambiguity (pt-BR + en mixed) — 10
 *   E. Follow-ups (context-dependent short replies) — 7
 *   F. Implicit contradiction (user asks "simple" for complex task) — 5
 *   G. Domain specialized (security/perf/auth) — 10
 *
 * Each case includes:
 *   - prompt: the user message
 *   - analysis: a fully-specified TaskAnalysis (what we expect the analyzer to produce)
 *   - expectedTier: the tier the decision matrix should pick given this analysis
 *   - adjacentOk: (optional) a second acceptable tier (edge cases where ± 1 tier is fine)
 *   - category: which category this case belongs to
 *   - notes: what the case is testing
 *
 * The runner applies the decision matrix to the analysis and verifies the tier.
 * We do NOT run the analyzer itself — that's integration testing. Golden
 * tests validate the decision matrix logic with pre-validated inputs.
 */

export type GoldenCase = {
  id: string
  category: "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H"
  prompt: string
  agent?: string
  analysis: TaskAnalysis
  expectedTier: Tier
  adjacentOk?: Tier[]
  notes: string
}

// Helper to build a full analysis with sensible defaults
function mkAnalysis(partial: Partial<TaskAnalysis>): TaskAnalysis {
  return {
    task_type: "standard_implementation",
    task_type_evidence: "default",
    reasoning_depth: "medium",
    reasoning_depth_evidence: "default",
    scope_breadth: "single_file",
    estimated_files_touched: 1,
    context_requirements: "moderate",
    ambiguity: "clear",
    ambiguity_reasons: [],
    risk_level: "medium",
    risk_justification: "default",
    novelty: "standard",
    detected_technologies: [],
    domain_expertise: "generic",
    iteration_profile: "single_shot",
    recommended_model: "sonnet",
    confidence: 0.85,
    primary_reasoning: "default",
    contrarian_check: "default",
    ...partial,
  }
}

export const GOLDEN_CASES: GoldenCase[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // CATEGORY A — Obvious tier (base calibration)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "A01",
    category: "A",
    prompt: "fix the typo 'recieve' → 'receive' in README.md line 42",
    analysis: mkAnalysis({
      task_type: "simple_edit",
      task_type_evidence: "single-character typo fix with exact location",
      reasoning_depth: "none",
      reasoning_depth_evidence: "pure find-and-replace",
      scope_breadth: "single_line",
      estimated_files_touched: 1,
      context_requirements: "minimal",
      ambiguity: "specific",
      risk_level: "low",
      risk_justification: "documentation change, no runtime effect",
      iteration_profile: "single_shot",
    }),
    expectedTier: "haiku",
    notes: "textbook haiku — all minimalist conditions met",
  },
  {
    id: "A02",
    category: "A",
    prompt: "qual a diferença entre Promise.all e Promise.allSettled?",
    analysis: mkAnalysis({
      task_type: "question_answer",
      task_type_evidence: "conceptual question about two JS built-ins",
      reasoning_depth: "shallow",
      reasoning_depth_evidence: "canonical comparison",
      scope_breadth: "single_line",
      estimated_files_touched: 0,
      context_requirements: "minimal",
      ambiguity: "specific",
      risk_level: "low",
      risk_justification: "pure explanation",
      domain_expertise: "language_specific",
      iteration_profile: "single_shot",
    }),
    expectedTier: "haiku",
    notes: "language Q&A → haiku",
  },
  {
    id: "A03",
    category: "A",
    prompt: "implementa um endpoint POST /users com validação via zod no fastify",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      task_type_evidence: "new endpoint following known pattern",
      reasoning_depth: "medium",
      scope_breadth: "multi_file_same_module",
      estimated_files_touched: 3,
      context_requirements: "moderate",
      ambiguity: "clear",
      risk_level: "medium",
      domain_expertise: "framework_specific",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "sonnet",
    notes: "standard impl → sonnet workhorse",
  },
  {
    id: "A04",
    category: "A",
    prompt:
      "refactor the entire database layer to switch from Postgres to CockroachDB, keeping the ORM abstraction intact but handling distributed transactions and retry-on-abort semantics. Need to plan rollout with zero downtime and coordinate with the read replicas.",
    analysis: mkAnalysis({
      task_type: "complex_refactor",
      reasoning_depth: "deep",
      scope_breadth: "system_wide",
      estimated_files_touched: 80,
      context_requirements: "repo_wide",
      ambiguity: "clear",
      risk_level: "critical",
      domain_expertise: "specialized",
      iteration_profile: "long_session",
    }),
    expectedTier: "opus-plan",
    adjacentOk: ["opus"],
    notes: "complex_refactor + long_session → opus-plan",
  },
  {
    id: "A05",
    category: "A",
    prompt: "add a `// TODO: review` comment above the getUser function",
    analysis: mkAnalysis({
      task_type: "simple_edit",
      reasoning_depth: "none",
      scope_breadth: "single_line",
      estimated_files_touched: 1,
      context_requirements: "minimal",
      ambiguity: "specific",
      risk_level: "low",
      iteration_profile: "single_shot",
    }),
    expectedTier: "haiku",
    notes: "comment insertion",
  },
  {
    id: "A06",
    category: "A",
    prompt: "explain the CAP theorem with an example from a distributed system",
    analysis: mkAnalysis({
      task_type: "question_answer",
      reasoning_depth: "shallow",
      scope_breadth: "single_line",
      estimated_files_touched: 0,
      context_requirements: "minimal",
      ambiguity: "specific",
      risk_level: "low",
      domain_expertise: "generic",
      iteration_profile: "single_shot",
    }),
    expectedTier: "haiku",
    notes: "explanation → haiku",
  },
  {
    id: "A07",
    category: "A",
    prompt: "write unit tests for the calculateTax function using vitest",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "medium",
      scope_breadth: "single_file",
      estimated_files_touched: 1,
      context_requirements: "moderate",
      ambiguity: "clear",
      risk_level: "low",
      domain_expertise: "framework_specific",
      iteration_profile: "single_shot",
    }),
    expectedTier: "sonnet",
    notes: "test writing → sonnet (not haiku because mid reasoning)",
  },
  {
    id: "A08",
    category: "A",
    prompt:
      "design an event-sourced microservice architecture for a trading platform that must handle 50k tx/sec with sub-10ms latency and full audit trail",
    analysis: mkAnalysis({
      task_type: "architectural",
      reasoning_depth: "exhaustive",
      scope_breadth: "system_wide",
      estimated_files_touched: null,
      context_requirements: "repo_wide",
      ambiguity: "clear",
      risk_level: "critical",
      novelty: "uncommon",
      domain_expertise: "specialized",
      iteration_profile: "marathon",
    }),
    expectedTier: "opus-plan",
    adjacentOk: ["opus"],
    notes: "architectural + marathon → opus-plan",
  },
  {
    id: "A09",
    category: "A",
    prompt: "rename variable `userData` to `accountData` in src/auth/session.ts",
    analysis: mkAnalysis({
      task_type: "simple_edit",
      reasoning_depth: "none",
      scope_breadth: "single_file",
      estimated_files_touched: 1,
      context_requirements: "minimal",
      ambiguity: "specific",
      risk_level: "low",
      iteration_profile: "single_shot",
    }),
    expectedTier: "haiku",
    notes: "scoped rename → haiku",
  },
  {
    id: "A10",
    category: "A",
    prompt: "list all files in the src/ directory modified in the last week",
    analysis: mkAnalysis({
      task_type: "trivial_lookup",
      task_type_evidence: "file listing query",
      reasoning_depth: "none",
      scope_breadth: "single_line",
      estimated_files_touched: 0,
      context_requirements: "minimal",
      ambiguity: "specific",
      risk_level: "low",
      iteration_profile: "single_shot",
    }),
    expectedTier: "haiku",
    notes: "file lookup → haiku",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CATEGORY B — Deceptively simple (look easy, actually risky)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "B01",
    category: "B",
    prompt: "corrige o typo na função de validação de CPF",
    analysis: mkAnalysis({
      task_type: "simple_edit",
      reasoning_depth: "shallow",
      scope_breadth: "single_file",
      estimated_files_touched: 1,
      context_requirements: "moderate",
      ambiguity: "clear",
      risk_level: "high",
      risk_justification: "CPF validation silently affects fraud detection",
      domain_expertise: "specialized",
      iteration_profile: "single_shot",
    }),
    expectedTier: "opus",
    notes: "specialized domain + high risk escalates to opus even if task looks simple",
  },
  {
    id: "B02",
    category: "B",
    prompt: "rename the `amount` field to `amountCents` everywhere",
    analysis: mkAnalysis({
      task_type: "complex_refactor",
      task_type_evidence: "'everywhere' implies system_wide rename with semantic shift",
      reasoning_depth: "deep",
      scope_breadth: "system_wide",
      estimated_files_touched: 45,
      context_requirements: "repo_wide",
      ambiguity: "ambiguous",
      ambiguity_reasons: [
        "the rename implies a unit change (units → cents) which may require data migration",
        "'everywhere' may include DB schema, API contracts, frontend, docs",
      ],
      risk_level: "critical",
      risk_justification: "unit confusion in money is financial liability",
      domain_expertise: "specialized",
      iteration_profile: "long_session",
    }),
    expectedTier: "opus-plan",
    adjacentOk: ["opus"],
    notes: "'rename' hides a semantic/unit change with financial risk",
  },
  {
    id: "B03",
    category: "B",
    prompt: "replace 'http://' with 'https://' in all config files",
    analysis: mkAnalysis({
      task_type: "simple_edit",
      reasoning_depth: "shallow",
      scope_breadth: "multi_file_same_module",
      estimated_files_touched: 15,
      context_requirements: "moderate",
      ambiguity: "clear",
      risk_level: "high",
      risk_justification: "scheme change can break connections to internal services without TLS",
      iteration_profile: "single_shot",
    }),
    expectedTier: "sonnet",
    notes: "looks like find-replace but scope + risk escalates above haiku",
  },
  {
    id: "B04",
    category: "B",
    prompt: "fix the off-by-one in the pagination loop",
    analysis: mkAnalysis({
      task_type: "simple_edit",
      reasoning_depth: "medium",
      scope_breadth: "single_file",
      estimated_files_touched: 1,
      context_requirements: "moderate",
      ambiguity: "clear",
      risk_level: "medium",
      iteration_profile: "single_shot",
    }),
    expectedTier: "sonnet",
    notes: "off-by-one needs actual reasoning (medium depth)",
  },
  {
    id: "B05",
    category: "B",
    prompt: "delete the commented-out code in auth.ts",
    analysis: mkAnalysis({
      task_type: "simple_edit",
      reasoning_depth: "none",
      scope_breadth: "single_file",
      estimated_files_touched: 1,
      context_requirements: "minimal",
      ambiguity: "clear",
      ambiguity_reasons: ["'commented-out' may include license headers and TODOs"],
      risk_level: "low",
      iteration_profile: "single_shot",
    }),
    expectedTier: "haiku",
    notes: "cleanup → haiku (ambig=clear is allowed by relaxed matrix)",
  },
  {
    id: "B06",
    category: "B",
    prompt: "update the SQL schema: add a created_at timestamp to users table",
    analysis: mkAnalysis({
      task_type: "simple_edit",
      reasoning_depth: "shallow",
      scope_breadth: "multi_file_same_module",
      estimated_files_touched: 3,
      context_requirements: "moderate",
      ambiguity: "clear",
      risk_level: "high",
      risk_justification: "schema changes on production tables require migration safety",
      domain_expertise: "specialized",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "opus",
    notes: "schema change on specialized domain → opus",
  },
  {
    id: "B07",
    category: "B",
    prompt: "change the log level from INFO to DEBUG",
    analysis: mkAnalysis({
      task_type: "simple_edit",
      reasoning_depth: "none",
      scope_breadth: "single_file",
      estimated_files_touched: 1,
      context_requirements: "minimal",
      ambiguity: "specific",
      risk_level: "low",
      iteration_profile: "single_shot",
    }),
    expectedTier: "haiku",
    notes: "trivial config change",
  },
  {
    id: "B08",
    category: "B",
    prompt: "add `strict: true` to tsconfig.json",
    analysis: mkAnalysis({
      task_type: "simple_edit",
      reasoning_depth: "shallow",
      scope_breadth: "system_wide",
      estimated_files_touched: 1,
      context_requirements: "repo_wide",
      ambiguity: "clear",
      risk_level: "high",
      risk_justification: "strict mode surfaces latent type errors across the whole codebase",
      iteration_profile: "long_session",
    }),
    expectedTier: "opus",
    notes: "system_wide scope from a 1-line change",
  },
  {
    id: "B09",
    category: "B",
    prompt: "update the API version from v1 to v2 in the client",
    analysis: mkAnalysis({
      task_type: "simple_edit",
      reasoning_depth: "medium",
      scope_breadth: "multi_file_same_module",
      estimated_files_touched: 8,
      context_requirements: "moderate",
      ambiguity: "ambiguous",
      ambiguity_reasons: ["API v2 may have breaking changes not yet reviewed"],
      risk_level: "high",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "sonnet",
    notes: "version bump can be trivial or breaking — escalate to sonnet",
  },
  {
    id: "B10",
    category: "B",
    prompt: "fix the bug in the password hashing",
    analysis: mkAnalysis({
      task_type: "debug_investigation",
      reasoning_depth: "deep",
      scope_breadth: "single_file",
      estimated_files_touched: 1,
      context_requirements: "moderate",
      ambiguity: "ambiguous",
      ambiguity_reasons: ["no description of the bug"],
      risk_level: "critical",
      risk_justification: "auth hashing bug is a security incident",
      domain_expertise: "specialized",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "opus",
    notes: "security + critical + debug → opus",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CATEGORY C — Deceptively complex (look hard, are mechanical)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "C01",
    category: "C",
    prompt: "refactor all 50 microservices to use Pino instead of Winston for logging",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      task_type_evidence: "library swap, repetitive pattern",
      reasoning_depth: "shallow",
      scope_breadth: "system_wide",
      estimated_files_touched: 150,
      context_requirements: "moderate",
      ambiguity: "clear",
      risk_level: "medium",
      domain_expertise: "language_specific",
      iteration_profile: "long_session",
    }),
    expectedTier: "opus",
    notes: "system_wide scope triggers opus even though task is mechanical",
  },
  {
    id: "C02",
    category: "C",
    prompt: "Explain Kubernetes operators in detail — include examples of CRDs and controllers",
    analysis: mkAnalysis({
      task_type: "question_answer",
      reasoning_depth: "shallow",
      scope_breadth: "single_line",
      estimated_files_touched: 0,
      context_requirements: "minimal",
      ambiguity: "specific",
      risk_level: "low",
      domain_expertise: "framework_specific",
      iteration_profile: "single_shot",
    }),
    expectedTier: "haiku",
    notes: "'complete architecture' sounding but is a Q&A",
  },
  {
    id: "C03",
    category: "C",
    prompt: "massively update all dependencies to latest — package.json + lockfile",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "shallow",
      scope_breadth: "single_file",
      estimated_files_touched: 2,
      context_requirements: "minimal",
      ambiguity: "clear",
      risk_level: "medium",
      iteration_profile: "single_shot",
    }),
    expectedTier: "sonnet",
    notes: "dep update is mechanical, sonnet suffices",
  },
  {
    id: "C04",
    category: "C",
    prompt: "copy the README.md template from .github/templates/ to all 30 repo folders",
    analysis: mkAnalysis({
      task_type: "simple_edit",
      reasoning_depth: "none",
      scope_breadth: "system_wide",
      estimated_files_touched: 30,
      context_requirements: "minimal",
      ambiguity: "specific",
      risk_level: "low",
      iteration_profile: "single_shot",
    }),
    expectedTier: "opus",
    adjacentOk: ["sonnet"],
    notes: "scope_breadth=system_wide triggers opus by rule",
  },
  {
    id: "C05",
    category: "C",
    prompt:
      "create a comprehensive getting started guide for new developers — cover setup, tools, workflow",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "medium",
      scope_breadth: "single_file",
      estimated_files_touched: 1,
      context_requirements: "moderate",
      ambiguity: "clear",
      risk_level: "low",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "sonnet",
    notes: "documentation is standard work, not architectural",
  },
  {
    id: "C06",
    category: "C",
    prompt: "modernize all class components to hooks in the React app",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "medium",
      scope_breadth: "cross_module",
      estimated_files_touched: 80,
      context_requirements: "moderate",
      ambiguity: "clear",
      risk_level: "medium",
      domain_expertise: "framework_specific",
      iteration_profile: "long_session",
    }),
    expectedTier: "opus",
    adjacentOk: ["opus-plan"],
    notes: "cross_module scope → opus",
  },
  {
    id: "C07",
    category: "C",
    prompt: "Lista os 10 maiores endpoints do backend por linhas de código",
    analysis: mkAnalysis({
      task_type: "trivial_lookup",
      reasoning_depth: "none",
      scope_breadth: "single_line",
      estimated_files_touched: 0,
      context_requirements: "extensive",
      ambiguity: "specific",
      risk_level: "low",
      iteration_profile: "single_shot",
    }),
    expectedTier: "sonnet",
    notes: "context=extensive prevents haiku trigger",
  },
  {
    id: "C08",
    category: "C",
    prompt: "generate TypeScript types from our GraphQL schema using codegen",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "shallow",
      scope_breadth: "single_file",
      estimated_files_touched: 2,
      context_requirements: "moderate",
      ambiguity: "clear",
      risk_level: "low",
      domain_expertise: "framework_specific",
      iteration_profile: "single_shot",
    }),
    expectedTier: "sonnet",
    notes: "codegen is mechanical",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CATEGORY D — Linguistic ambiguity (pt-BR + en mixed)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "D01",
    category: "D",
    prompt: "melhora a performance",
    analysis: mkAnalysis({
      task_type: "research",
      reasoning_depth: "deep",
      scope_breadth: "unclear",
      estimated_files_touched: null,
      context_requirements: "extensive",
      ambiguity: "vague",
      ambiguity_reasons: [
        "performance of what?",
        "latency / throughput / memory / startup?",
        "no baseline",
      ],
      risk_level: "medium",
      domain_expertise: "specialized",
      iteration_profile: "long_session",
    }),
    expectedTier: "opus",
    notes: "vague perf task → opus (research + deep)",
  },
  {
    id: "D02",
    category: "D",
    prompt: "tá quebrado em prod, help",
    analysis: mkAnalysis({
      task_type: "debug_investigation",
      reasoning_depth: "exhaustive",
      scope_breadth: "unclear",
      estimated_files_touched: null,
      context_requirements: "repo_wide",
      ambiguity: "vague",
      ambiguity_reasons: ["what is 'quebrado'? errors? performance? crash?"],
      risk_level: "high",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "opus",
    notes: "emergency debug → opus",
  },
  {
    id: "D03",
    category: "D",
    prompt: "Can you help me with the login stuff? something isn't working",
    analysis: mkAnalysis({
      task_type: "debug_investigation",
      reasoning_depth: "medium",
      scope_breadth: "cross_module",
      estimated_files_touched: null,
      context_requirements: "extensive",
      ambiguity: "vague",
      ambiguity_reasons: ["'stuff' and 'something' are both undefined"],
      risk_level: "high",
      domain_expertise: "specialized",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "opus",
    notes: "vague auth debug → opus",
  },
  {
    id: "D04",
    category: "D",
    prompt: "faz aquela coisa que a gente tava conversando",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "medium",
      scope_breadth: "unclear",
      estimated_files_touched: null,
      context_requirements: "extensive",
      ambiguity: "vague",
      ambiguity_reasons: ["no prior context in this turn"],
      risk_level: "medium",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "sonnet",
    notes: "vague reference, no deep trigger → default sonnet",
  },
  {
    id: "D05",
    category: "D",
    prompt: "pega o user, valida o cpf, salva no db — tudo isso numa function só",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "medium",
      scope_breadth: "single_file",
      estimated_files_touched: 1,
      context_requirements: "moderate",
      ambiguity: "clear",
      risk_level: "high",
      domain_expertise: "specialized",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "opus",
    notes: "specialized (cpf validation) + non-QA → opus",
  },
  {
    id: "D06",
    category: "D",
    prompt: "arruma esse arquivo por favor",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "medium",
      scope_breadth: "single_file",
      estimated_files_touched: 1,
      context_requirements: "moderate",
      ambiguity: "vague",
      ambiguity_reasons: ["'arruma' = fix? refactor? format? unclear"],
      risk_level: "medium",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "sonnet",
    notes: "vague but no deep trigger → sonnet",
  },
  {
    id: "D07",
    category: "D",
    prompt: "run: npm test",
    analysis: mkAnalysis({
      task_type: "trivial_lookup",
      task_type_evidence: "command execution, not even code",
      reasoning_depth: "none",
      scope_breadth: "single_line",
      estimated_files_touched: 0,
      context_requirements: "minimal",
      ambiguity: "specific",
      risk_level: "low",
      iteration_profile: "single_shot",
    }),
    expectedTier: "haiku",
    notes: "command execution → haiku",
  },
  {
    id: "D08",
    category: "D",
    prompt: "O que o comando `git reflog --date=iso --all` faz?",
    analysis: mkAnalysis({
      task_type: "question_answer",
      reasoning_depth: "shallow",
      scope_breadth: "single_line",
      estimated_files_touched: 0,
      context_requirements: "minimal",
      ambiguity: "specific",
      risk_level: "low",
      domain_expertise: "generic",
      iteration_profile: "single_shot",
    }),
    expectedTier: "haiku",
    notes: "documentation query → haiku",
  },
  {
    id: "D09",
    category: "D",
    prompt: "testa se o deploy funcionou",
    analysis: mkAnalysis({
      task_type: "trivial_lookup",
      reasoning_depth: "shallow",
      scope_breadth: "single_line",
      estimated_files_touched: 0,
      context_requirements: "minimal",
      ambiguity: "ambiguous",
      ambiguity_reasons: ["which environment?", "what 'working' means here?"],
      risk_level: "medium",
      iteration_profile: "single_shot",
    }),
    expectedTier: "sonnet",
    notes: "ambiguity escalates from haiku",
  },
  {
    id: "D10",
    category: "D",
    prompt: "cachear a resposta do endpoint /users usando redis",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "medium",
      scope_breadth: "multi_file_same_module",
      estimated_files_touched: 3,
      context_requirements: "moderate",
      ambiguity: "clear",
      risk_level: "medium",
      domain_expertise: "framework_specific",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "sonnet",
    notes: "feature add → sonnet",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CATEGORY E — Follow-ups (short, context-dependent)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "E01",
    category: "E",
    prompt: "sim",
    analysis: mkAnalysis({
      task_type: "trivial_lookup",
      reasoning_depth: "none",
      scope_breadth: "single_line",
      estimated_files_touched: 0,
      context_requirements: "minimal",
      ambiguity: "ambiguous",
      ambiguity_reasons: ["context is the prior turn, not this message"],
      risk_level: "low",
      iteration_profile: "single_shot",
    }),
    expectedTier: "sonnet",
    notes: "follow-up — ambiguous without context, escalated from haiku",
  },
  {
    id: "E02",
    category: "E",
    prompt: "não é isso, refaz",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "medium",
      scope_breadth: "unclear",
      estimated_files_touched: null,
      context_requirements: "moderate",
      ambiguity: "ambiguous",
      ambiguity_reasons: ["no hint at what was wrong"],
      risk_level: "medium",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "sonnet",
    notes: "correction follow-up → sonnet default",
  },
  {
    id: "E03",
    category: "E",
    prompt: "continua",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "medium",
      scope_breadth: "unclear",
      estimated_files_touched: null,
      context_requirements: "moderate",
      ambiguity: "ambiguous",
      risk_level: "medium",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "sonnet",
    notes: "continuation → sonnet",
  },
  {
    id: "E04",
    category: "E",
    prompt: "ok, próximo passo",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "medium",
      scope_breadth: "unclear",
      estimated_files_touched: null,
      context_requirements: "moderate",
      ambiguity: "clear",
      risk_level: "medium",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "sonnet",
    notes: "short continuation",
  },
  {
    id: "E05",
    category: "E",
    prompt: "por que esse código não tá compilando?",
    analysis: mkAnalysis({
      task_type: "debug_investigation",
      reasoning_depth: "medium",
      scope_breadth: "single_file",
      estimated_files_touched: 1,
      context_requirements: "moderate",
      ambiguity: "clear",
      risk_level: "low",
      iteration_profile: "single_shot",
    }),
    expectedTier: "sonnet",
    notes: "debug question → sonnet",
  },
  {
    id: "E06",
    category: "E",
    prompt: "manda o diff",
    analysis: mkAnalysis({
      task_type: "trivial_lookup",
      reasoning_depth: "none",
      scope_breadth: "single_line",
      estimated_files_touched: 0,
      context_requirements: "minimal",
      ambiguity: "specific",
      risk_level: "low",
      iteration_profile: "single_shot",
    }),
    expectedTier: "haiku",
    notes: "display request → haiku",
  },
  {
    id: "E07",
    category: "E",
    prompt: "agora vamos pro problema do cache que ficou pendente",
    analysis: mkAnalysis({
      task_type: "research",
      reasoning_depth: "deep",
      scope_breadth: "cross_module",
      estimated_files_touched: null,
      context_requirements: "extensive",
      ambiguity: "ambiguous",
      risk_level: "high",
      domain_expertise: "specialized",
      iteration_profile: "long_session",
    }),
    expectedTier: "opus",
    notes: "context shift marker + research task",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CATEGORY F — Implicit contradiction
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "F01",
    category: "F",
    prompt:
      "quero uma solução simples e rápida pra fazer autenticação OAuth2 com refresh tokens, rate limiting e audit log",
    analysis: mkAnalysis({
      task_type: "architectural",
      reasoning_depth: "deep",
      scope_breadth: "cross_module",
      estimated_files_touched: 10,
      context_requirements: "moderate",
      ambiguity: "clear",
      risk_level: "critical",
      domain_expertise: "specialized",
      iteration_profile: "long_session",
    }),
    expectedTier: "opus-plan",
    adjacentOk: ["opus"],
    notes: "user says 'simple' but task is architectural",
  },
  {
    id: "F02",
    category: "F",
    prompt: "faz rapidinho uma migração do banco de dados mono→multi-tenant",
    analysis: mkAnalysis({
      task_type: "complex_refactor",
      reasoning_depth: "exhaustive",
      scope_breadth: "system_wide",
      estimated_files_touched: 50,
      context_requirements: "repo_wide",
      ambiguity: "clear",
      risk_level: "critical",
      domain_expertise: "specialized",
      iteration_profile: "marathon",
    }),
    expectedTier: "opus-plan",
    adjacentOk: ["opus"],
    notes: "'rapidinho' vs multi-tenant migration = contradiction",
  },
  {
    id: "F03",
    category: "F",
    prompt: "quick fix — the entire app is crashing on startup in production",
    analysis: mkAnalysis({
      task_type: "debug_investigation",
      reasoning_depth: "exhaustive",
      scope_breadth: "system_wide",
      estimated_files_touched: null,
      context_requirements: "repo_wide",
      ambiguity: "vague",
      risk_level: "critical",
      iteration_profile: "marathon",
    }),
    expectedTier: "opus",
    notes: "'quick fix' contradicted by severity",
  },
  {
    id: "F04",
    category: "F",
    prompt: "trivial change: swap our entire ORM from Prisma to Drizzle",
    analysis: mkAnalysis({
      task_type: "complex_refactor",
      reasoning_depth: "deep",
      scope_breadth: "system_wide",
      estimated_files_touched: 100,
      context_requirements: "repo_wide",
      ambiguity: "clear",
      risk_level: "high",
      domain_expertise: "framework_specific",
      iteration_profile: "marathon",
    }),
    expectedTier: "opus-plan",
    adjacentOk: ["opus"],
    notes: "'trivial' + ORM swap contradiction",
  },
  {
    id: "F05",
    category: "F",
    prompt: "easy one: redesign our event sourcing model to handle retroactive corrections",
    analysis: mkAnalysis({
      task_type: "architectural",
      reasoning_depth: "exhaustive",
      scope_breadth: "system_wide",
      estimated_files_touched: 40,
      context_requirements: "repo_wide",
      ambiguity: "clear",
      risk_level: "critical",
      novelty: "novel",
      domain_expertise: "specialized",
      iteration_profile: "marathon",
    }),
    expectedTier: "opus-plan",
    adjacentOk: ["opus"],
    notes: "novel + architectural + critical",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CATEGORY G — Domain specialized
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "G01",
    category: "G",
    prompt: "fix the race condition in the payment processor when a refund races with a capture",
    analysis: mkAnalysis({
      task_type: "debug_investigation",
      reasoning_depth: "deep",
      scope_breadth: "cross_module",
      estimated_files_touched: 5,
      context_requirements: "extensive",
      ambiguity: "clear",
      risk_level: "critical",
      novelty: "novel",
      domain_expertise: "specialized",
      iteration_profile: "long_session",
    }),
    expectedTier: "opus",
    notes: "critical race condition → opus",
  },
  {
    id: "G02",
    category: "G",
    prompt: "audit the JWT validation — I think there's an algorithm confusion vulnerability",
    analysis: mkAnalysis({
      task_type: "review",
      reasoning_depth: "deep",
      scope_breadth: "cross_module",
      estimated_files_touched: 4,
      context_requirements: "extensive",
      ambiguity: "clear",
      risk_level: "critical",
      novelty: "uncommon",
      domain_expertise: "specialized",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "opus",
    notes: "security audit → opus",
  },
  {
    id: "G03",
    category: "G",
    prompt: "optimize the hot path in our matching engine from 50μs to <10μs",
    analysis: mkAnalysis({
      task_type: "research",
      reasoning_depth: "exhaustive",
      scope_breadth: "multi_file_same_module",
      estimated_files_touched: 3,
      context_requirements: "extensive",
      ambiguity: "clear",
      risk_level: "high",
      novelty: "novel",
      domain_expertise: "specialized",
      iteration_profile: "marathon",
    }),
    expectedTier: "opus-plan",
    adjacentOk: ["opus"],
    notes: "low-latency perf → opus-plan (marathon + research)",
  },
  {
    id: "G04",
    category: "G",
    prompt: "write a function to validate an ISBN-13 checksum",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "shallow",
      scope_breadth: "single_file",
      estimated_files_touched: 1,
      context_requirements: "minimal",
      ambiguity: "specific",
      risk_level: "low",
      domain_expertise: "generic",
      iteration_profile: "single_shot",
    }),
    expectedTier: "sonnet",
    notes: "new function code is standard_implementation — sonnet workhorse (not haiku because task_type is new-code, not a trivial edit)",
  },
  {
    id: "G05",
    category: "G",
    prompt: "add Argon2id password hashing to the login flow",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "medium",
      scope_breadth: "multi_file_same_module",
      estimated_files_touched: 3,
      context_requirements: "moderate",
      ambiguity: "clear",
      risk_level: "high",
      domain_expertise: "specialized",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "opus",
    notes: "specialized auth work → opus",
  },
  {
    id: "G06",
    category: "G",
    prompt: "reduce memory usage of our streaming ETL pipeline",
    analysis: mkAnalysis({
      task_type: "research",
      reasoning_depth: "deep",
      scope_breadth: "cross_module",
      estimated_files_touched: 6,
      context_requirements: "extensive",
      ambiguity: "clear",
      risk_level: "medium",
      novelty: "uncommon",
      domain_expertise: "specialized",
      iteration_profile: "long_session",
    }),
    expectedTier: "opus-plan",
    adjacentOk: ["opus"],
    notes: "perf research → opus-plan",
  },
  {
    id: "G07",
    category: "G",
    prompt: "what's the difference between a semaphore and a mutex?",
    analysis: mkAnalysis({
      task_type: "question_answer",
      reasoning_depth: "shallow",
      scope_breadth: "single_line",
      estimated_files_touched: 0,
      context_requirements: "minimal",
      ambiguity: "specific",
      risk_level: "low",
      domain_expertise: "specialized",
      iteration_profile: "single_shot",
    }),
    expectedTier: "haiku",
    notes: "specialized domain but task_type=question_answer bypasses escalation",
  },
  {
    id: "G08",
    category: "G",
    prompt: "implement CSRF protection for our form submission endpoints",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "medium",
      scope_breadth: "multi_file_same_module",
      estimated_files_touched: 4,
      context_requirements: "moderate",
      ambiguity: "clear",
      risk_level: "high",
      domain_expertise: "specialized",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "opus",
    notes: "specialized (security) → opus",
  },
  {
    id: "G09",
    category: "G",
    prompt: "convert the FIX messages to our internal order model",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "medium",
      scope_breadth: "single_file",
      estimated_files_touched: 2,
      context_requirements: "moderate",
      ambiguity: "clear",
      risk_level: "high",
      domain_expertise: "specialized",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "opus",
    notes: "trading protocol specialized → opus",
  },
  {
    id: "G10",
    category: "G",
    prompt: "what's the time complexity of heapify?",
    analysis: mkAnalysis({
      task_type: "question_answer",
      reasoning_depth: "shallow",
      scope_breadth: "single_line",
      estimated_files_touched: 0,
      context_requirements: "minimal",
      ambiguity: "specific",
      risk_level: "low",
      iteration_profile: "single_shot",
    }),
    expectedTier: "haiku",
    notes: "algorithm Q&A → haiku",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CATEGORY H — REAL-WORLD cases from OpenCode DB analysis (7388 sessions)
  // Extracted from /tmp/real-prompts.txt and /tmp/suggested-golden-cases.md
  // Represents actual user patterns (not synthetic).
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "H01",
    category: "H",
    agent: "explore",
    prompt:
      "[CONTEXT]: I'm reviewing how the CRM loads and displays conversation lists. [GOAL]: Understand how conversation lists load initially, how status is displayed, and how the list updates when attendance changes. [REQUEST]: Find in front/src/ directory the relevant files.",
    analysis: mkAnalysis({
      task_type: "research",
      reasoning_depth: "medium",
      scope_breadth: "cross_module",
      estimated_files_touched: null,
      context_requirements: "extensive",
      ambiguity: "clear",
      risk_level: "low",
      iteration_profile: "long_session",
    }),
    expectedTier: "haiku",
    adjacentOk: ["sonnet"],
    notes: "explore agent override forces haiku — investigation task from real DB",
  },
  {
    id: "H02",
    category: "H",
    agent: "multimodal-looker",
    prompt: 'Called the Read tool with the following input: {"filePath":"/tmp/after_login.png"}',
    analysis: mkAnalysis({
      task_type: "trivial_lookup",
      reasoning_depth: "none",
      scope_breadth: "single_line",
      estimated_files_touched: 0,
      context_requirements: "minimal",
      ambiguity: "specific",
      risk_level: "low",
      iteration_profile: "single_shot",
    }),
    expectedTier: "haiku",
    notes: "multimodal-looker image read — highest-volume real case",
  },
  {
    id: "H03",
    category: "H",
    agent: "sisyphus-junior",
    prompt:
      "## 1. TASK\nImplement Task 2 of the screen-lock-v2 plan: Add isScreenLocked and lockMessage fields to the Zustand TV store, with atomic selectors.\n\n## 2. EXPECTED OUTCOME\n- [ ] isScreenLocked: boolean added to SimplifiedTVStore interface\n- [ ] lockMessage: string | null added\n- [ ] Initial values added to state.ts",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "medium",
      scope_breadth: "multi_file_same_module",
      estimated_files_touched: 3,
      context_requirements: "moderate",
      ambiguity: "specific",
      risk_level: "medium",
      domain_expertise: "framework_specific",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "sonnet",
    notes: "Sisyphus-Junior implementation — real pattern with ## TASK structure",
  },
  {
    id: "H04",
    category: "H",
    agent: "explore",
    prompt:
      "CONTEXT: Analisando sistema IndoorTec que tem gastos excessivos no CloudFront. GOAL: Encontrar testes E2E existentes. QUESTION: Quais testes E2E existem? Há testes relacionados a mídia/CloudFront?",
    analysis: mkAnalysis({
      task_type: "research",
      reasoning_depth: "medium",
      scope_breadth: "cross_module",
      estimated_files_touched: null,
      context_requirements: "extensive",
      ambiguity: "clear",
      risk_level: "low",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "haiku",
    adjacentOk: ["sonnet"],
    notes: "explore pt-BR structured research task",
  },
  {
    id: "H05",
    category: "H",
    agent: "oracle",
    prompt:
      "[CONTEXT]: Security review of cross-platform authentication system between 3 applications using magic links for SSO. The system generates 256-bit tokens, stores SHA-256 hash in Redis. [REQUEST]: Audit for vulnerabilities including token reuse, timing attacks, CSRF.",
    analysis: mkAnalysis({
      task_type: "review",
      reasoning_depth: "deep",
      scope_breadth: "cross_module",
      estimated_files_touched: 8,
      context_requirements: "extensive",
      ambiguity: "clear",
      risk_level: "critical",
      novelty: "uncommon",
      domain_expertise: "specialized",
      iteration_profile: "long_session",
    }),
    expectedTier: "opus",
    notes: "oracle security review — real pattern, agent override forces opus",
  },
  {
    id: "H06",
    category: "H",
    agent: "explore",
    prompt:
      "[CONTEXT]: I'm auditing a React Native TV app for memory leaks. Any setInterval/setTimeout/addEventListener not cleaned up is a leak. [GOAL]: Find every timer, interval, event listener, and subscription across app/ to verify they all have proper cleanup.",
    analysis: mkAnalysis({
      task_type: "research",
      reasoning_depth: "deep",
      scope_breadth: "cross_module",
      estimated_files_touched: null,
      context_requirements: "repo_wide",
      ambiguity: "clear",
      risk_level: "medium",
      domain_expertise: "framework_specific",
      iteration_profile: "long_session",
    }),
    expectedTier: "haiku",
    adjacentOk: ["sonnet"],
    notes: "explore audit task — agent override wins even with deep reasoning",
  },
  {
    id: "H07",
    category: "H",
    agent: "sisyphus-junior",
    prompt:
      "## TASK\nImplement 7 security fixes for the farmaeasy-app backend. ## EXPECTED OUTCOME - All 7 fixes implemented - ruff check passes - ruff format check passes - pytest passes. ## REQUIRED TOOLS - Read, Edit, Bash. ## MUST DO — ALL 7 FIXES. ### FIX C1: Validate JWT secret is not the default...",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "medium",
      scope_breadth: "multi_file_same_module",
      estimated_files_touched: 7,
      context_requirements: "moderate",
      ambiguity: "specific",
      risk_level: "high",
      domain_expertise: "specialized",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "sonnet",
    notes: "Sisyphus-Junior security fixes — structured task, agent override to sonnet",
  },
  {
    id: "H08",
    category: "H",
    agent: "sisyphus",
    prompt:
      "# Task: Fix totem card current media name resolution\n\n## Working Directory\n`/path/to/project/web-wt/fix/868j41mc5-totem-card-current-media`\n\n## Bug Description\nThe totem card and TV detail page 'Mídia Atual' section display the original filename instead of the user-renamed name for the currently playing media.\n\n**Root cause**: `currentMedia.name` comes from...",
    analysis: mkAnalysis({
      task_type: "debug_investigation",
      reasoning_depth: "medium",
      scope_breadth: "cross_module",
      estimated_files_touched: 5,
      context_requirements: "moderate",
      ambiguity: "specific",
      risk_level: "medium",
      domain_expertise: "framework_specific",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "opus",
    notes: "Sisyphus agent with structured bug description — agent override to opus",
  },
  {
    id: "H09",
    category: "H",
    agent: "explore",
    prompt:
      "I'm analyzing the Redis caching layer for race conditions, cache stampede, and concurrency bugs. FIND: 1. The @redis_cache decorator implementation — does it use locks for cache stampede prevention? 2. What happens on cache miss + concurrent requests? 3. Is there a singleflight mechanism?",
    analysis: mkAnalysis({
      task_type: "debug_investigation",
      reasoning_depth: "deep",
      scope_breadth: "multi_file_same_module",
      estimated_files_touched: 3,
      context_requirements: "extensive",
      ambiguity: "clear",
      risk_level: "high",
      novelty: "uncommon",
      domain_expertise: "specialized",
      iteration_profile: "short_dialog",
    }),
    expectedTier: "haiku",
    adjacentOk: ["sonnet"],
    notes: "explore even for specialized debugging — agent override is absolute",
  },
  {
    id: "H10",
    category: "H",
    agent: "librarian",
    prompt: "Find the latest Zod v4 breaking changes and migration path from v3",
    analysis: mkAnalysis({
      task_type: "research",
      reasoning_depth: "shallow",
      scope_breadth: "single_line",
      estimated_files_touched: 0,
      context_requirements: "minimal",
      ambiguity: "specific",
      risk_level: "low",
      domain_expertise: "framework_specific",
      iteration_profile: "single_shot",
    }),
    expectedTier: "haiku",
    notes: "librarian doc lookup — simple external research task",
  },

  // ─── Display-name normalization cases ────────────────────────────────
  // These verify that agent names arriving as DISPLAY NAMES from the TUI
  // (e.g. "Sisyphus (Ultraworker)") are correctly mapped to config keys
  // for the agent override lookup. Without normalization, sisyphus users
  // would bypass the opus override and hit the default workhorse (sonnet).
  {
    id: "H11",
    category: "H",
    agent: "Sisyphus (Ultraworker)",
    prompt: "implement a complex authentication refactor spanning auth, session, and rate limiting",
    analysis: mkAnalysis({
      task_type: "complex_refactor",
      reasoning_depth: "deep",
      scope_breadth: "cross_module",
      risk_level: "critical",
    }),
    expectedTier: "opus",
    adjacentOk: ["opus-plan"],
    notes:
      "Sisyphus has NO override (it's the default agent for ALL prompts). Decision comes from analysis: complex_refactor + deep + cross_module → opus.",
  },
  {
    id: "H12",
    category: "H",
    agent: "Sisyphus (Ultraworker)",
    prompt: "responda ping",
    analysis: mkAnalysis({
      task_type: "question_answer",
      reasoning_depth: "none",
      scope_breadth: "single_line",
      estimated_files_touched: 0,
      context_requirements: "minimal",
      ambiguity: "specific",
      risk_level: "low",
      iteration_profile: "single_shot",
    }),
    expectedTier: "haiku",
    notes:
      "Sisyphus with trivial prompt → analyzer/matrix decides haiku (sisyphus NOT in overrides anymore — it's the catch-all agent).",
  },
  {
    id: "H13",
    category: "H",
    agent: "Hephaestus (Deep Agent)",
    prompt: "build a feature",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "medium",
      scope_breadth: "multi_file_same_module",
    }),
    expectedTier: "sonnet",
    notes: "Hephaestus display name → 'hephaestus' → sonnet override",
  },
  {
    id: "H14",
    category: "H",
    agent: "Sisyphus-Junior",
    prompt: "add a null check",
    analysis: mkAnalysis({
      task_type: "simple_edit",
      reasoning_depth: "shallow",
      scope_breadth: "single_line",
      estimated_files_touched: 1,
      context_requirements: "minimal",
      ambiguity: "specific",
      risk_level: "low",
      iteration_profile: "single_shot",
    }),
    expectedTier: "sonnet",
    notes: "Sisyphus-Junior display name → 'sisyphus-junior' → sonnet override",
  },
  {
    id: "H15",
    category: "H",
    agent: "Atlas (Plan Executor)",
    prompt: "execute the plan step 3",
    analysis: mkAnalysis({
      task_type: "standard_implementation",
      reasoning_depth: "medium",
    }),
    expectedTier: "sonnet",
    notes: "Atlas display name → 'atlas' → sonnet override",
  },
  {
    id: "H16",
    category: "H",
    agent: "Metis (Plan Consultant)",
    prompt: "should we use microservices or a monolith for this project?",
    analysis: mkAnalysis({
      task_type: "research",
      reasoning_depth: "deep",
      scope_breadth: "cross_module",
    }),
    expectedTier: "opus",
    notes: "Metis display name → 'metis' → opus override (matches analysis anyway)",
  },
]

export function countByCategory(): Record<string, number> {
  const counts: Record<string, number> = { A: 0, B: 0, C: 0, D: 0, E: 0, F: 0, G: 0 }
  for (const c of GOLDEN_CASES) counts[c.category] = (counts[c.category] ?? 0) + 1
  return counts
}
